### ISSUE TITLE
Please link from the plugin description to this git repo

### ISSUE THREAD

**Issue by reinderien** [exbin/bined-intellij-plugin#15]
It would be helpful if the plugin description within the JetBrains interface showed a link here, instead of to the generic project (deltahex.exbin.org).

**Comment by hajdam** [comment]
Domain change and separate page for this plugin are relatively new and still under construction.
I updated [plugin page](https://plugins.jetbrains.com/plugin/9339-deltahex-editor) for now. Plugin name should be changed with first 0.2 release.
