### ISSUE TITLE
Editor stops responding when I use Find

### ISSUE THREAD

**Issue by joswhite** [exbin/bined-intellij-plugin#19]
Steps to reproduce:
- I open a certificate file (.p12) in Webstorm using the "Open as Hex" option under the "File" menu
- The hex file opens properly
- I use the Ctrl-F shortcut to open the Find box and begin typing text.
- The editor stops responding and I have to shut it down using End Task.

**Comment by hajdam** [comment]
I don't have Webstorm, but I tested, that there is the same issue in the most recent version of idea. I'll take look into it.

**Comment by joswhite** [comment]
Thanks!

**Comment by hajdam** [comment]
I tried to mitigate this in version 0.2.2. Searching is still quirky thou. Hopefully I'll have some time to improve it in the future...
