### ISSUE TITLE
File can only be opened by clicking "Open As Binary"

### ISSUE THREAD

**Issue by Kimi-Arthur** [exbin/bined-intellij-plugin#21]
Awesome tool indeed!

I've found a strange bug using bined with Rider for a binary file named `data.bin`.

If you click on a binary file, it will open a blank bined editor. If you then use "Open As Binary", it will create a new blank bined editor.

If you close all those windows and right click on the file and select "Open As Binary", it works properly.

I guess the first experience should be similar to the second. Hope that will be fixed!

**Comment by hajdam** [comment]
Hi, I was testing association with .bin files at some point and forget to remove it.

It was part of next level of integration which would allow to show Binary tab on any file and share file content with other tabs, which is planned for some future release.

I removed .bin association in development version for now if it bothers you (if you have many .bin files for example) and need to use default IntelliJ behavior.

**Comment by Kimi-Arthur** [comment]
That helps actually! Thanks a lot! I can then open the file and launch the tool.

But of course, once you got the association working, that will even better!

**Comment by hajdam** [comment]
Should be mitigated in 0.2.1
