### ISSUE TITLE
add automatic refresh feature

### ISSUE THREAD

**Issue by Sauci** [exbin/bined-intellij-plugin#23]
It would be great if the plugin could update the displayed content if the file was modified (touch'ed) externally.

**Comment by hajdam** [comment]
Hi. Plugin currently supports delta memory mode, which can't support this by definition. But native wrapper to IntelliJ file handling might be possible, just not any time soon...

**Comment by hajdam** [comment]
Native file wrapper was added in version 0.2.3. To use it, it is necessary to associate file with "Binary File" file type in Options/Editor/File Types settings. "Open as Binary" actions still doesn't reflect external changes automatically.
