### ISSUE TITLE
Cursor position is lost if you switch tabs

### ISSUE THREAD

**Issue by ibarrac** [exbin/bined-intellij-plugin#25]
In IntelliJ, if you have your cursor set on a specific hex byte, like when you are examining a binary field, then you switch tabs to another source file you want to look at by pressing Ctrl-tab, then switch back to the BinEd hex display, the cursor is gone and you don't know where you were before.

It is important for the cursor to remain where it was because it acts like a placeholder. For example, you may be in the middle of decoding a complex binary structure and writing parsing code in another source file so you need to switch back and forth without losing your place.

Using BinEd v 0.2.1 and IntelliJ IDEA 2019.3 on Windows.

**Comment by hajdam** [comment]
Actually this is an issue with focus - component loses focus when windows are switched for some reason. I'll try to look into it.

**Comment by hajdam** [comment]
Should be fixed in version 0.2.2.
