### ISSUE TITLE
Display the number of bytes selected

### ISSUE THREAD

**Issue by ibarrac** [exbin/bined-intellij-plugin#26]
It would be great if the number of bytes currently selected could be displayed somewhere like in one of the panes at the bottom. That would make it simpler to understand where a binary field ends.

Currently, it displays the cursor position but to know where a field ends you have to do the arithmetic in your head to add the field length to that position, instead of simply selecting the bytes until that display would read the right field length.

**Comment by hajdam** [comment]
You are right and I saw that in some other editors, but didn't have time to do that yet.
I'll try to go with selection size instead of document size and selection start + end in cursor position when selection is active.

**Comment by hajdam** [comment]
Added to version 0.2.2.
