### ISSUE TITLE
High dpi doesn't scale correctly

### ISSUE THREAD

**Issue by SUPERCILEX** [exbin/bined-intellij-plugin#33]
On a 4K monitor, the toolbar and settings pane looks super teeny:
![image](https://user-images.githubusercontent.com/9490724/99760983-dd906700-2aa9-11eb-9020-779d776fa508.png)
![image](https://user-images.githubusercontent.com/9490724/99761020-eda84680-2aa9-11eb-9c71-5f41938c7763.png)
![image](https://user-images.githubusercontent.com/9490724/99761027-f567eb00-2aa9-11eb-88e7-ecd5e3ad48c1.png)

**Comment by hajdam** [comment]
I tried to check this in latest version, but it behaves differently probably because of the newer Java version used in IntelliJ...
Not sure what to do about this anyway, so closing.
If it's still an issue for you, please reopen.
