### ISSUE TITLE
2021.1: Can't close any tabs once a binary file is opened

### ISSUE THREAD

**Issue by AzureMarker** [exbin/bined-intellij-plugin#35]
In CLion 2021.1, once you open a binary file it is impossible to close any tabs or open new files. You can't switch tabs or close the project either. The whole IDE must be restarted.

**Comment by hajdam** [comment]
Hi, thanks for your report. I cannot confirm this yet, hopefully my OS license will be renewed, so I'll check CLion then.

If possible, could you include information about platform/java version?

**Comment by Mcat12** [comment]
I'm running on Fedora 33, and here's CLion's info:
![image](https://user-images.githubusercontent.com/4417660/114212269-a246e580-992f-11eb-9b26-6b5603fe31d3.png)

**Comment by hajdam** [comment]
I had same issue when I updated IntelliJ today. Hopefully fixed in current dev build:
https://bined.exbin.org/download/?bined-intellij-plugin.zip

Will test it further and hopefully release soon.

**Comment by Mcat12** [comment]
That build fixed the issue for me!

**Comment by quickstep24** [comment]
Yes, problem also applies to Intellij. As long as your have another Tab open, you can close by choosing "close other tabs" there. Or you can try "reopen last tab" to get back another tab.
Hopefully we can get an update soon.

**Comment by hajdam** [comment]
Should be fixed in version 0.2.4.
