### ISSUE TITLE
How to increase font size?

### ISSUE THREAD

**Issue by euneuber** [exbin/bined-intellij-plugin#37]
The editor font size is not used in this plugin. How can I increase the font size to match the editor font?

(4k monitor here)

**Comment by hajdam** [comment]
Hi. When editing file via plugin open Options dialog via last toolbar icon or context popup menu and navigate to "Font" category and press "Change font" button.

**Comment by hajdam** [comment]
Assuming answer was sufficient. There is a plan to support shortcuts to change font size on the fly, but it's deep in TODO list...
