### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Znunu** [exbin/bined-intellij-plugin#38]
The block with the raw bytes isn't transparent and doesn't show my background, unlike everything else on my pycharm IDE. To make it worse, whenever I click on something anywhere (doesn't have to be somewhere within the plugin) or even just unfocus the window then the background briefly appears, before going away again. The end result is almost like a flash. It's really unpleasant and distracting. I tried tinkering with theme profiles but it didn't help.

**Comment by hajdam** [comment]
Hi. I'm not sure if I understand. Could you provide screenshot or information about what special background or plugin are you using and your platform? (Win/Mac/Linux?)

**Comment by Znunu** [comment]
Thanks for looking into my problem

My OS is Windows 10
I am using the built in background image feature
![image](https://user-images.githubusercontent.com/61394004/129462013-7db1ce10-bfe1-47c1-950e-81ae4ada4b78.png)
I have attached an recording

https://user-images.githubusercontent.com/61394004/129462059-556e88a5-be95-4543-b6c9-1bb04f462464.mp4

**Comment by hajdam** [comment]
It seems, that IntelliJ platform uses special components for it's editors to propagate background images and attempts to do that for regular swing components at least partially as well.

I tried some experimental workaround, but it doesn't work all the time. Hopefully at least code area should flicker less with it...

If you want, you can try current development build, although there are some known issues with editing and many more untested bugs as it is work-in-progress...
https://bined.exbin.org/download/?bined-intellij-plugin.zip

Not sure I'll be able to do much more about this issue. Maybe I'll try to investigate around more before next release :-/

**Comment by Znunu** [comment]
Thank you so much for taking your time to look into this!

Definitely often see the background break in pycharm, even sometimes without plugins. Anyway, I tried it and it works great! The background shows and everything blends seamlessly.  Everything looks great now.
![image](https://user-images.githubusercontent.com/61394004/129650090-dbbeb888-0ce6-41cf-b1f0-d6d4273d33fc.png)
You said it doesn't work all the time. It has worked for me until now..... but maybe I've got lucky?

However confused about something else. If I enter the settings screen and press apply or save (without changing any settings), the layout changes. When I reopen the tab, I'm back to the initial layout. I'm guessing this is one of those issues you mentioned?

Thank you again for working on this project. Hex editor seems like an essential thing to have in your IDE.

**Comment by hajdam** [comment]
Well, it doesn't work all the time in values panel on the right side, bottom status panel and search toolbar. But it doesn't flicker there much at least...

As for saving, it seems that there is currently bug, that font is not applied when new tab is opened, therefore when saved, font will change. There might be other issues, but I didn't notice them...

As for hex editor in IDE, it's easy to use external hex editor with much more capabilities. Also not many developers need to look into binary data these days anyway. For me primary need for this plugin was to show debug fields as binary data.

**Comment by hajdam** [comment]
Font issue is hopefully fixed in current development build.

**Comment by Znunu** [comment]
Thanks! Yes, it fixed the font issue! Everything works here. There are some exceptions, but they don't really seem to cause any problems?

You can close this issue if you want

**Comment by hajdam** [comment]
If you think there are some exceptions related to the plugin, you can include it here... I didn't notice any at my short testing.

**Comment by Znunu** [comment]
I'm not sure. It says `Exception in plugin Bin-Ed`. There were four.

[1.txt](https://github.com/exbin/bined-intellij-plugin/files/7001272/1.txt)  `java.lang.StackOverflowError`
[2.txt](https://github.com/exbin/bined-intellij-plugin/files/7001269/2.txt)  `java.lang.StackOverflowError`
[3.txt](https://github.com/exbin/bined-intellij-plugin/files/7001270/3.txt)  `java.lang.StackOverflowError`
[4.txt](https://github.com/exbin/bined-intellij-plugin/files/7001271/4.txt) `java.lang.ClassCastException`

**Comment by hajdam** [comment]
Thanks. It all seems to be related :-/ I'll try to fix it...

**Comment by Znunu** [comment]
good luck

**Comment by Znunu** [comment]
I tired reproducing them again, but really couldn't. Maybe it's nothing
Glad that you fixed the other errors though

**Comment by hajdam** [comment]
Should be fixed in version 0.2.5.
