### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by HoldYourWaffle** [exbin/bined-intellij-plugin#44]
Title says it all :)

No matter what I change, everything is reverted when I click OK :(
The "Apply" button is also never enabled, perhaps that's related?

```
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Kotlin: 222-1.7.10-release-334-IJ3739.54
```

**Comment by hajdam** [comment]
Hi, thanks for your report.
It seems that there is some issue with settings page integration. I'll try to look into it.
In the mean time, feel free to use settings window from toolbar or context menu - when editing file via BinEd plugin.

**Comment by hajdam** [comment]
Seems that page has to be reported as modified so that save/apply method is called :-/ 
Updated current development build:
https://bined.exbin.org/download/?bined-intellij-plugin.zip
