### ISSUE TITLE
Layout, theme and color profile settings are hidden behind scrollbar inception

### ISSUE THREAD

**Issue by HoldYourWaffle** [exbin/bined-intellij-plugin#45]
Title says it all :)

<img src="https://user-images.githubusercontent.com/11472320/185764220-df653f22-2da2-42e3-8db7-64d8520a282d.png" width="600">
<img src="https://user-images.githubusercontent.com/11472320/185764251-e3c6599b-60c3-4ce7-9b0d-4bd3129ebd5f.png" width="600">
<img src="https://user-images.githubusercontent.com/11472320/185764265-8c5c3718-9338-4c50-8448-2ef96ccf3b66.png" width="600">

```
IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Kotlin: 222-1.7.10-release-334-IJ3739.54
```

**Comment by hajdam** [comment]
Hi, thanks for reporting this.
I fixed it in BinEd and forgot to copy the fix to plugin. :-/
Development build updated:
https://bined.exbin.org/download/?bined-intellij-plugin.zip
