### ISSUE TITLE
It would be nice to add a binary comparison feature

### ISSUE THREAD

**Issue by meiMingle** [exbin/bined-intellij-plugin#48]

**Comment by hajdam** [comment]
There is basic byte-for-byte comparison window you can open using Compare files action in context popup menu when editing file using BinEd plugin.
https://bined.exbin.org/intellij-plugin/?manual#compare-files-action

Better comparison and better integration into IntelliJ is planned, but not in near future...

**Comment by hajdam** [comment]
Added byte-to-byte compare diff option in currently released version 0.2.8.
Better variants still not planned for near future.
