### ISSUE TITLE
Live reload feature

### ISSUE THREAD

**Issue by xahon** [exbin/bined-intellij-plugin#49]
When file is changed outside it should reload the buffer (Probably ask first, intellij doesn't ask for a regular text files)

**Comment by xahon** [comment]
Oh, I found that if you associate the file with "BinEd Plugin" filetype then live-reload works as expected. Probably should work with "Open As Binary" action as well, or it is by design?

**Comment by hajdam** [comment]
When using "Open as Binary" file is opened independently and changes are not automatically saved - reloading would mean losing unsaved changes.
Also there are two modes - one loads whole file into memory and the other stores only changed partsof file - it should open files with exclusive write lock, but there is no correct implementation finished yet.

**Comment by hajdam** [comment]
Added basic reload action for partial mode which asks if changes should be written.
(write lock maybe in some far future release)
Version 0.2.8 released.
