### ISSUE TITLE
Cant delete/overwrite file when closed/

### ISSUE THREAD

**Issue by aimjel** [exbin/bined-intellij-plugin#53]
Viewing a file as binary and then closing the viewer and trying to delete the file causes an error: `The process cannot access the file because it is being used by another process`

Reproduce:
1. Open file as binary
2. Close the viewer for the file
3. Delete file/Overwrite file

I'm using the latest GoLand version (2023.2.3), but this problem also occurred while using version 2023.2.2.

**Comment by hajdam** [comment]
Duplicate of #34 
I believe it's the same as the linked issue.
If you are willing to, please test current development build (install plugin from downloaded file) and let me know, if it solves your issue:
https://bined.exbin.org/download/?bined-intellij-plugin.zip

**Comment by aimjel** [comment]
I tested the development build you linked and it worked, thank you!
