### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by craigday** [exbin/bined-intellij-plugin#56]
Any changes you make to files using this plugin are not applied when you save or close the relevant tab.

IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  FrameSwitcher (4.5.0-232.7295)
  org.intellij.plugins.hcl (233.13135.65)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  com.intellij.guice (233.11799.196)
  String Manipulation (9.12.0)
  com.intellij.ml.llm (233.14015.147)
  com.github.copilot (1.5.0.5148)
  org.exbin.deltahex.intellij (0.2.9)
  com.dmarcotte.handlebars (233.11799.172)
  mobi.hsz.idea.gitignore (4.5.2)
  io.kanro.idea.plugin.protobuf (1.7.50)
Kotlin: 233.14015.106-IJ

**Comment by hajdam** [comment]
Hi, thanks for your report, but as there is no exception included (usually under blinking red exclamation icon in right bottom side of Idea) and I don't have any macOS 14 / M2+ system available for testing, I don't think I can do much here.
It could be some kind of file writing protection or specific file handling issue in macOS.

As there were some event handling changes in 2023.3, could you also try current development build - via Settings/Plugins/Gear icon/Install plugin from disk?
https://bined.exbin.org/download/?f=bined-intellij-plugin.zip

If possible you:
- check whether there is any error reported about BinEd plugin in idea.log file in Help/Show log in File Manager
- check whether file was opened / locked by other tabs or applications at the same time
- describe specific steps how the file was opened - was it part of the project or from filesystem?

**Comment by hajdam** [comment]
Released version 0.2.10 which could have this fixed.

Closing as this issue as there was no response.
