### ISSUE TITLE
Content crashes when panes are manipulated

### ISSUE THREAD

**Issue by reinderien** [exbin/bined-intellij-plugin#7]
Several actions in PyCharm cause the hex editor's content to crash. This can be triggered by 

- Moving the hex editor to the opposite group
- Moving an unrelated editor to its opposite group

When the content crashes, the editor is still open, but the file appears empty (zero-length).

**Comment by hajdam** [comment]
Partially fixed in 0.2.1 (but works only when single window is opened and moved)

**Comment by hajdam** [comment]
It seems to be working correctly in post 2019 releases. Probably won't fix for older ones.
