### ISSUE TITLE
Add a string decoder to the list of casts on the right

### ISSUE THREAD

**Issue by reinderien** [exbin/bined-intellij-plugin#8]
It would be very useful to show a decoder on the right for strings using the charset selected under the "active encoding" control on the bottom.

This could allow for null termination, or keep processing until an invalid encoding sequence is encountered.

This is different from the "raw" content displayed in the right-hand half of the window, because that's obliged to keep a one-to-one correspondence between characters and bytes, but a proper decoder would not have that restriction.

**Comment by hajdam** [comment]
Currently each text preview character for UTF-8 is constructed from up-to 8 bytes, but it starts decoding on exact position to match "raw" content.
Also it's possible to enter/copy/paste unicode characters and text and it will insert/overwrite proper number of bytes.

Encoding for characters with variable lengths with skipping bytes would cause misalignment issues.
For this purpose "String" field was considered for values panel, but it was not yet implemented.

**Comment by hajdam** [comment]
Added simple string field to values panel in version 0.2.4.

More options might be coming, but not any time soon :-I
